package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.45

import (
	"context"

	"github.com/edwinlomolo/drago-api/graph/model"
)

// Courier is the resolver for the courier field.
func (r *tripResolver) Courier(ctx context.Context, obj *model.Trip) (*model.Courier, error) {
	return r.tc.GetTripCourier(ctx, *obj.CourierID)
}

// Trip returns TripResolver implementation.
func (r *Resolver) Trip() TripResolver { return &tripResolver{r} }

type tripResolver struct{ *Resolver }
