// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.24.0

package db

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type Business struct {
	ID                 uuid.UUID   `json:"id"`
	BusinessType       string      `json:"business_type"`
	Name               string      `json:"name"`
	Phone              string      `json:"phone"`
	HasInHouseLogistic bool        `json:"has_in_house_logistic"`
	Logo               string      `json:"logo"`
	Location           interface{} `json:"location"`
	DateCreated        time.Time   `json:"date_created"`
	UserID             uuid.UUID   `json:"user_id"`
	CreatedAt          time.Time   `json:"created_at"`
	UpdatedAt          time.Time   `json:"updated_at"`
}

type Courier struct {
	ID         uuid.UUID      `json:"id"`
	Firstname  string         `json:"firstname"`
	Lastname   string         `json:"lastname"`
	Phone      string         `json:"phone"`
	Verified   bool           `json:"verified"`
	Location   interface{}    `json:"location"`
	FcmToken   sql.NullString `json:"fcm_token"`
	Status     string         `json:"status"`
	Ratings    float64        `json:"ratings"`
	Points     int32          `json:"points"`
	BusinessID uuid.UUID      `json:"business_id"`
	ProductID  uuid.NullUUID  `json:"product_id"`
	CreatedAt  time.Time      `json:"created_at"`
	UpdatedAt  time.Time      `json:"updated_at"`
}

type Product struct {
	ID           uuid.UUID     `json:"id"`
	Name         string        `json:"name"`
	Descriptions string        `json:"descriptions"`
	WeightClass  int32         `json:"weight_class"`
	Icon         string        `json:"icon"`
	Relevance    int32         `json:"relevance"`
	BusinessID   uuid.NullUUID `json:"business_id"`
	CreatedAt    time.Time     `json:"created_at"`
	UpdatedAt    time.Time     `json:"updated_at"`
}

type Session struct {
	ID        uuid.UUID      `json:"id"`
	UserAgent sql.NullString `json:"user_agent"`
	Ip        sql.NullString `json:"ip"`
	Expired   sql.NullTime   `json:"expired"`
	UserID    uuid.NullUUID  `json:"user_id"`
	CreatedAt time.Time      `json:"created_at"`
	UpdatedAt time.Time      `json:"updated_at"`
}

type Trip struct {
	ID             uuid.UUID     `json:"id"`
	PickupAddress  string        `json:"pickup_address"`
	DropoffAddress string        `json:"dropoff_address"`
	PickUp         interface{}   `json:"pick_up"`
	DropOff        interface{}   `json:"drop_off"`
	CourierID      uuid.NullUUID `json:"courier_id"`
	Status         string        `json:"status"`
	Cost           sql.NullInt32 `json:"cost"`
	BusinessID     uuid.UUID     `json:"business_id"`
	CreatedAt      time.Time     `json:"created_at"`
	UpdatedAt      time.Time     `json:"updated_at"`
}

type User struct {
	ID         uuid.UUID      `json:"id"`
	Firstname  string         `json:"firstname"`
	Lastname   string         `json:"lastname"`
	Phone      sql.NullString `json:"phone"`
	Email      string         `json:"email"`
	Onboarding bool           `json:"onboarding"`
	CreatedAt  time.Time      `json:"created_at"`
	UpdatedAt  time.Time      `json:"updated_at"`
}
