// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.24.0

package db

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	ClearTestBusinesses(ctx context.Context) (int64, error)
	ClearTestCouriers(ctx context.Context) (int64, error)
	ClearTestSessions(ctx context.Context) (int64, error)
	ClearTestTrips(ctx context.Context) (int64, error)
	ClearTestUsers(ctx context.Context) (int64, error)
	CountUsers(ctx context.Context) (int64, error)
	CreateBusiness(ctx context.Context, arg CreateBusinessParams) (Business, error)
	CreateBusinessProduct(ctx context.Context, arg CreateBusinessProductParams) (Product, error)
	CreateCourier(ctx context.Context, arg CreateCourierParams) (Courier, error)
	CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error)
	CreateTrip(ctx context.Context, arg CreateTripParams) (Trip, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DestroySession(ctx context.Context, userID uuid.NullUUID) (Session, error)
	FinishOnboarding(ctx context.Context, id uuid.UUID) (Session, error)
	GetBusinessBelongingToUser(ctx context.Context, userID uuid.UUID) ([]GetBusinessBelongingToUserRow, error)
	GetBusinessCouriers(ctx context.Context, businessID uuid.UUID) ([]GetBusinessCouriersRow, error)
	GetBusinessProducts(ctx context.Context, businessID uuid.NullUUID) ([]GetBusinessProductsRow, error)
	GetCourierByID(ctx context.Context, id uuid.UUID) (Courier, error)
	GetCourierByPhone(ctx context.Context, phone string) (Courier, error)
	GetSession(ctx context.Context, userID uuid.NullUUID) (Session, error)
	GetTripsBelongingToBusiness(ctx context.Context, businessID uuid.UUID) ([]GetTripsBelongingToBusinessRow, error)
	GetUser(ctx context.Context, email string) (User, error)
	GetUsersByID(ctx context.Context, ids []uuid.UUID) ([]User, error)
}

var _ Querier = (*Queries)(nil)
